name: HomburgPlots
version: '${project.version}'
main: tech.justcoding.homburgplots.Main
api-version: 1.19
authors: [ justCoding ]
commands:
  manageplot:
    description: Manage plots on the server (add/remove)